### ISSUE TITLE
Mantener escuchando canción.

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#10]
Investigar sobre cómo puede hacerse para escuchar la música que esta sonando en cada una de las interfaces de la aplicación, ya que actualmente solo se reproduce en una pestaña.
Desarrollar el widget de la barra inferior que informa qué canción esta sonando.

En el caso de ser excesivamente complicado, hablar con el resto del equipo para restructurar la aplicación.

**Comment by aFacorroLoscos** [comment]
Se ha descubierto el como mantener la aplicación activa en las demás Interfaces de la aplicación.
No se ha llegado a implementar pero a cambio se ha mejorado la reproducción de la aplicación información al usuario dentro de la pestaña de notificaciones el estado actual de la canción .
