### ISSUE TITLE
Perfiles de usuarios

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#11]
Perfil de usuario.
Perfil del artista junto a los albums que tiene.

**Comment by luisgg98** [comment]
Mostrar el perfil de usuario, su foto, su nombre y las listas de reproduccion que ha escuchado.

**Comment by oscarbaselga** [comment]
Implementada la pantalla de los perfiles en la que se muestran los datos del usuario y sus playlists.
