### ISSUE TITLE
Investigar API podscast

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#12]
Investigar cómo se usa la API de Listen Notes o si hay alguna alternativa para Flutter.
No empezar a implementar nada, simplemente buscar cómo se harían las cosas y tener una idea que luego se pueda implementar sin estar horas.

**Comment by oscarbaselga** [comment]
Realizada una breve investigación sobre la API de los podcast en la plataforma Listen Notes.
