### ISSUE TITLE
Guardar y mostrar última LISTA DE REPRODUCCION

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#13]
Desarrollar la interfaz para el equalizador, buscar bibliotecas para flutter.

**Comment by luisgg98** [comment]
A lo mejor esto ayuda. 
https://flutterawesome.com/audio-input-mixer-ui-design-in-flutter/

**Comment by luisgg98** [comment]
Cada cierto tiempo guardar la última canción que ha reproducido el usuario y mostrarla en su perfil.

**Comment by aFacorroLoscos** [comment]
Guardo y muestro la ultima cancion. Me falta mostrarla en el perfil

**Comment by aFacorroLoscos** [comment]
Hecho
