### ISSUE TITLE
Mantener estado canción

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#20]
Hasta ahora es posible escuchar un lista de reproducción en el móvil, pero no podemos controlar las canciones desde el resto de la aplicación. Es necesario transmitir el estado de la música.

**Comment by luisgg98** [comment]
Barra auxiliar que se encuentra en la parte inferior de la aplicación debe estar funcional.

**Comment by aFacorroLoscos** [comment]
Hecho, la barra auxiliar está en toda interfaz que usamos
