### ISSUE TITLE
Login automático

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#31]
Los artistas van a mostrar sus listas de reproducción.
Los usuarios han de poder seleccionar una lista de reproducción y agregarla a las suyas o pinchar en las canciones y agregarlas a listas de reproducción que ya tenga hechas.

**Comment by luisgg98** [comment]
En flutter no existe la clase cookie. Pero existe shared_preferences, que son variables que se almacenan de forma local y que se pueden usar en cualquier momento.
https://stackoverflow.com/questions/41369633/how-to-save-to-local-storage-using-flutter

**Comment by aFacorroLoscos** [comment]
Donete, cuando puedas le echas un vistazo
