### ISSUE TITLE
Adaptar reproductor

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#34]
Adaptar reproductor al patrón singleton para utilizar solo una instancia del reproductor.
https://medium.com/flutter-community/flutter-design-patterns-1-singleton-437f04e923ce
https://www.youtube.com/watch?v=2GKZ5xu3Xhg

**Comment by aFacorroLoscos** [comment]
Por ahora solo está implementada en la interfaz de lista de canciones

**Comment by aFacorroLoscos** [comment]
Hecho en toda la aplicacion, adaptado, errores solucionados
