### ISSUE TITLE
Indicar el estado Podcast/Artista

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#59]
Cuando el usuario entre en podcast o en artistas y no hay nada puede resultar complicado entender en qué apartado esta o qué hacer esto.
Indicarle de alguna forma que esta ese menú sirve para que añada sus podcasts o que busque artistas.

**Comment by oscarbaselga** [comment]
Cuando estan vacias una de las listas, se muestra un mensaje explicativo.
