### ISSUE TITLE
Inicio de sesión y registro.

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#8]
Interfaces:
Iniciar sesión.
Registrarse.
Primera pantalla, donde te aparaece si tienes una cuenta y quieres iniciar sesión o si quieres registrarte.
(En general todo lo necesario para iniciar sesión en la aplicación y registrarse).

**Comment by oscarbaselga** [comment]
Implementadas las interfaces de inicio de sesión y registro, se han implementado las peticiones en backend pero no se han probado.
