### ISSUE TITLE
Pantalla principal.

### ISSUE THREAD

**Issue by luisgg98** [UNIZAR-30226-2020-10/front-end_android#9]
En el drive se llama "pantalla_de_inicio."
La pantalla donde aparecen las novedades, los géneros de música y las listas de reproducción de usuario.

**Comment by oscarbaselga** [comment]
Implementada la pantalla de inicio con su correspondiente navegación a las pantallas de inicio de sesión y registro.

**Comment by luisgg98** [comment]
Me refiero a esta interfaz perdona.
https://drive.google.com/drive/u/2/folders/1m2UVAPLAtpYcmnXxXLDVSi1IMRLNrL1u

**Comment by oscarbaselga** [comment]
Implementada la estructura de la pantalla principal, faltaría decidir cual es todo el contenido que debe tener e incorporarlo.

**Comment by luisgg98** [comment]
Mostrar las últimas canciones y las canciones por categoría.

**Comment by luisgg98** [comment]
Últimas canciones agregadas al sistema.
Las canciones de cada género/categoría musical(preguntar a Backend).

**Comment by oscarbaselga** [comment]
Pagina principal completa sujeta a cambios. Aparecen las últimas canciones añadidas y los generos musicales (ya operativos).
